### ISSUE TITLE
Need For Documentation

### ISSUE THREAD

**Issue by SwiftKraft** [TrickyBestia/PyPlugin#3]
The plugin is great and all, but I need a documentation for this, because I don't know what events exist and what effects it can do. If you can write a documentation explaining the things that you can do (no need to be to complex), it would be wonderful.

**Comment by TheUltiOne** [comment]
Hey, the documentation is actually Exiled.
[Exiled's GitHub page can be found here.](https://github.com/galaxy119/EXILED)

**Comment by SwiftKraft** [comment]
what do you mean by the documentation is Exiled?

**Comment by TheUltiOne** [comment]
Well, this is the Python version of Exiled so I kinda misphrased that. All the events are found there [in the Handlers folder](https://github.com/galaxy119/EXILED/tree/master/Exiled.Events/Handlers).

Also, in the EXILED Discord, they have all the EventArgs.
If you have any questions feel free to ask away.

**Comment by SwiftKraft** [comment]
Ok, thank you for your immediate response!

**Comment by TheUltiOne** [comment]
Oh also, since EXILED is made with C#, and you might not know it, ask for any questions. Like please do.

If you don't know what events exist, and can't bother to check out the C#, they also have it in separate files right [here](https://github.com/galaxy119/EXILED/tree/master/Exiled.Events/Patches/Events), in their HarmonyLib patches.

**Comment by SwiftKraft** [comment]
How do you like convert the events to python

**Comment by TheUltiOne** [comment]
You don't actually need to, they work like the player.onPlayerJoin example. [Link](https://github.com/TrickyBestia/PyPlugin/blob/master/ForDevelopers.md)

**Comment by SwiftKraft** [comment]
So do I just use the C# event name on the `def`?

**Comment by trickybestia** [comment]
@SwiftKraft you should subscribe handler to the event first. You can find example here https://github.com/TrickyBestia/PyPlugin/blob/master/PyPlugin.Example/plugin.py on 36-37 lines.

**Comment by trickybestia** [comment]
@SwiftKraft is your issue solved?

**Comment by SwiftKraft** [comment]
oh sorry for not responding, my issue is solved
